# Generated by Django 3.2.9 on 2021-11-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyClubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Venue Name')),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=50, verbose_name='Zip Code')),
                ('phone', models.CharField(max_length=50, verbose_name='Contact Phone')),
                ('web', models.URLField(max_length=50, verbose_name='Website Address')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email address')),
            ],
        ),
    ]
